-- Create a table for Team Chat
create table if not exists public.bento_chat (
  id bigint generated by default as identity primary key,
  content text not null,
  user_id uuid references auth.users not null default auth.uid(),
  username text, 
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Chat
alter table public.bento_chat enable row level security;

create policy "Enable read access for all users"
on public.bento_chat for select
using (true);

create policy "Enable insert for authenticated users"
on public.bento_chat for insert
with check (true); -- simplified for demo, ideally check auth.uid()

-- Create a table for Tasks
create table if not exists public.bento_tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  is_completed boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Tasks
alter table public.bento_tasks enable row level security;

create policy "Enable read access for all users"
on public.bento_tasks for select
using (true);

create policy "Enable insert/update for all users"
on public.bento_tasks for all
using (true);

-- Create a table for Project State (Progress)
create table if not exists public.bento_state (
  key text primary key,
  value jsonb
);

alter table public.bento_state enable row level security;
create policy "Public access" on public.bento_state for all using (true);

-- Insert initial progress if not exists
insert into public.bento_state (key, value)
values ('project_progress', '0')
on conflict (key) do nothing;
